#!/usr/bin/env python

#Import necissary modules and libraries
from sklearn.model_selection import train_test_split
import pandas as pd
import tensorflow as tf
import tensorflow_hub as hub
from datetime import datetime

#ensure we have BERT model from Tensorflow
!pip install bert-tensorflow

#Import and take dependencies from BERT
import bert
from bert import run_classifier
from bert import optimization
from bert import tokenization
